### ISSUE TITLE
Uncaught TypeError: Cannot read property 'clone' of undefined

### ISSUE THREAD

**Issue by AsiaCobra** [felipeelia/cf7-repeatable-fields#15] opened 2018-11-28 03:01 UTC
I got this error when i click add btn.

Uncaught TypeError: Cannot read property 'clone' of undefined
    at HTMLButtonElement.<anonymous> (scripts.min.js?ver=4.9.8:1)
    at HTMLBodyElement.dispatch (jquery-3.3.1.min.js:2)
    at HTMLBodyElement.y.handle (jquery-3.3.1.min.js:2)

**Comment by felipeelia** [comment] 2019-10-10 18:03
(Almost 1yr later...)
Sorry for taking this long to be back to you here but I could not reproduce this one @AsiaCobra. I'll close the issue (probably you already have that figured out) but feel free to provide more info if you can. Thanks!

**Closed by felipeelia** 2019-10-10 18:03 UTC
