### ISSUE TITLE
When enabled Contact Form 7 can't send emails

### ISSUE THREAD

**Issue by mardoqueo** [felipeelia/cf7-repeatable-fields#21] opened 2019-10-24 22:46 UTC

**Comment by felipeelia** [comment] 2019-10-24 22:49
HI @mardoqueo !

Can you please:
1. Share how are you testing this
2. How is your form configured

Thanks

**Comment by mardoqueo** [comment] 2019-10-24 22:54
Hello! These are all the plugins I'm using.


- 
- All-in-One WP Migration
- 
- All-in-One WP Migration Unlimited Extension
- 
- Contact Form 7
- 
- Contact Form 7 - Repeatable Fields
- 
- Contact Form 7 - Submission id
- 
- 	
- Contact Form 7 Auto Save Progress
- 
- Contact Form 7 Autocomplete (+ address Contact Form 7)
- 
- Contact Form 7 Builder And Designer
- 
- Contact Form 7 Color or Image field
- 
- Contact Form 7 Conditional logic
- 
- Contact Form 7 Constant Contact
- 
- Contact Form 7 Cost Calculator - Price Calculation
- 
- Contact Form 7 CRM - ZOHO CRM
- 
- Contact Form 7 Drag and Drop FIles Upload - Multiple Files Upload
- 
- 	
- Contact Form 7 International Telephone Input
- 
- 	
- Contact Form 7 Invitation Codes
- 
- Contact Form 7 Multi-step Pro
- 
- Contact Form 7 Paypal Pro
- 
- Contact Form 7 Polls
- 
- Contact Form 7 Popup
- 
- Contact Form 7 Recorder Field
- 
- Contact Form 7 Recover Abandoned Form
- 
- Contact Form 7 Redirects
- 
- Contact Form 7 Repeater
- 
- Contact Form 7 Save To Database / CSV / PDF
- 
- Contact Form 7 Star Rating Field
- 
- Contact Form 7 Tooltips
- 
- Contact Form 7 Webhooks
- 	
- Duplicar página
- 
- Envato Market
- 
- Google Analytics Dashboard for WP (GADWP)
- 
- Nginx Helper
- 
- Salient Core
- 
- Salient Shortcodes
- 
- Salient Widgets
- 
- Salient WPBakery Page Builder
- 
- SendGrid
- 
- Smush
- 
- Sucuri Security - Auditoría, detección de malware, y fortificación
- 
- SVG Support
- 

The form is using a couple of conditions and groups from contact-form-7-addon-bundle-all-in-one from codecanyon.
Whenever I enable yours the contact forms start giving ERROR.

**Comment by felipeelia** [comment] 2019-10-24 23:01
Oh, that could be an incompatibility problem indeed. Unfortunately, it is impossible to make an addon for CF7 fully compatible with all other addons :(

I'd recommend you to install the [Health Check](https://wordpress.org/plugins/health-check/) plugin and enable its troubleshooting mode. With that, enable CF7 and this plugin and then enable one by one the other add-ons to know which is incompatible with this addon. Knowing that it would be easier to reproduce, debug and fix the problem.

Thanks in advance!

**Comment by mardoqueo** [comment] 2019-10-25 19:24
Thanks Felipe!
Just did fresh wordpress install, without theme, just CF7 with your plugin and still get red error.

https://cap.mardoqueo.com.ar/7-2/

**Comment by felipeelia** [comment] 2019-10-25 20:20
Did you test just CF7? Also, how did you set the form?

**Comment by mardoqueo** [comment] 2019-10-25 20:50
Tried CF7 by itself and works. The form is just showing the repeater example in the plugin.

**Comment by felipeelia** [comment] 2019-10-26 00:36
Hmm, that is odd. I can't reproduce it here. How did you set up the email receiver?

**Comment by mardoqueo** [comment] 2019-10-26 19:48
Sory but I don't understand the question. Could you be more specific? I'd love to help get this fixed 👍

**Comment by felipeelia** [comment] 2019-10-27 00:01
Sorry, I meant the "To:" field in the "Mail" tab. Also, a couple of other questions:
- Which is your hosting company?
- Are you using Sendgrid to send the emails?

As I maintain this plugin in my spare time, I'll do my best to help you but please don't rely on my assistance to fix your question. I can be or can be not able to help you during the next days or weeks.

**Comment by mardoqueo** [comment] 2019-10-27 15:59
Great!

- Using Sendgrid, test email gets sent correctly.
- Emails sent when 'Repeatable fields' disabled.
- Hosted in DigitalOcean and using WordOps.

**Comment by felipeelia** [comment] 2019-10-27 19:46
Does it work when you have the plugin enabled but the form doesn't have any repeatable group?

**Comment by mardoqueo** [comment] 2019-10-28 18:09
No, enabling the plugin prevents forms from working at all.

**Comment by felipeelia** [comment] 2019-12-18 18:42
As this issue didn't have any activity during the last months, I'm closing it.

**Closed by felipeelia** 2019-12-18 18:42 UTC
Labels: 3rd party
